#Github Repository Actions Name
name: Java CI with Gradle

#Event Trigger : master branch push Event 발생 시 trigger 실행
on:
  push:
    branches: [ "master" ]

  #브랜치 push 이벤트 외에, 수동으로 실행하는 것도 가능하게 만드는 옵션.
  workflow_dispatch:

jobs:
  build:

    #해당 Github Actions 스크립트 작동될 OS 환경 지정
    runs-on: ubuntu-latest

    steps:
    #프로젝트 코드 체크아웃
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      #Github Actions 가 실행될 OS에 Java 11 설치
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Grant Execute Permsission for Gradlew
      #gradle wrapper를 실행할 수 있도록 실행 권한 부여(+x)
      #해당 권한을 부여해야 build 가 가능.
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      #gradle wrapper 를 통해 해당 프로젝트 build
      run: ./gradlew clean build
      shell: bash

#    - name: Build with Gradle
#      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#      with:
#        arguments: build
